### ISSUE TITLE
Cannot view Logs for device

### ISSUE THREAD

**Issue by tamimology** [imagegenius/docker-esphome#7]
since the recent 2 updates, I am not able to view any device's logs, not after update nor by clicking the logs button

The below screenshot is after I clicked LOGS (all devices showed a similar log)

![image](https://github.com/imagegenius/docker-esphome/assets/90429593/eb347b85-fd4d-4c9c-ba18-13c303cbe08f)

The below is the complete log after updating another device (all devices showed a similar log)
```
INFO ESPHome 2024.3.1
INFO Reading configuration /config/decoration-lights.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing decoration-lights (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
Compiling .pioenvs/decoration-lights/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/binary_sensor/filter.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/esp8266/core.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/esp8266/gpio.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/esp8266/preferences.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/gpio/switch/gpio_switch.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/logger/logger_esp32.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/logger/logger_esp8266.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/logger/logger_host.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/logger/logger_libretiny.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/logger/logger_rp2040.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/mdns/mdns_libretiny.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/ota/ota_backend_arduino_libretiny.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/socket/lwip_sockets_impl.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/status_led/status_led.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/switch/automation.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/switch/switch.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/wifi/wifi_component_libretiny.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/application.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/color.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/component.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/component_iterator.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/controller.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/entity_base.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/helpers.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/log.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/ring_buffer.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/scheduler.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/string_ref.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/time.cpp.o
Compiling .pioenvs/decoration-lights/src/esphome/core/util.cpp.o
Compiling .pioenvs/decoration-lights/src/main.cpp.o
Generating LD script .pioenvs/decoration-lights/ld/local.eagle.app.v6.common.ld
Compiling .pioenvs/decoration-lights/lib9ad/ESPAsyncTCP-esphome/AsyncPrinter.cpp.o
Compiling .pioenvs/decoration-lights/lib9ad/ESPAsyncTCP-esphome/ESPAsyncTCP.cpp.o
Compiling .pioenvs/decoration-lights/lib9ad/ESPAsyncTCP-esphome/ESPAsyncTCPbuffer.cpp.o
Compiling .pioenvs/decoration-lights/lib9ad/ESPAsyncTCP-esphome/SyncClient.cpp.o
Compiling .pioenvs/decoration-lights/lib9ad/ESPAsyncTCP-esphome/tcp_axtls.c.o
Compiling .pioenvs/decoration-lights/lib5f4/Hash/Hash.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/BearSSLHelpers.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/CertStoreBearSSL.cpp.o
Archiving .pioenvs/decoration-lights/lib5f4/libHash.a
Archiving .pioenvs/decoration-lights/lib9ad/libESPAsyncTCP-esphome.a
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/ESP8266WiFi.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/ESP8266WiFiAP.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/ESP8266WiFiGratuitous.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/ESP8266WiFiSTA-WPS.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/ESP8266WiFiScan.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/WiFiClient.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/WiFiClientSecureBearSSL.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/WiFiServer.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/WiFiServerSecureBearSSL.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/WiFiUdp.cpp.o
Compiling .pioenvs/decoration-lights/lib71b/ESP8266WiFi/enable_wifi_at_boot_time.cpp.o
Compiling .pioenvs/decoration-lights/libd7c/ESPAsyncWebServer-esphome/AsyncEventSource.cpp.o
Compiling .pioenvs/decoration-lights/libd7c/ESPAsyncWebServer-esphome/AsyncWebSocket.cpp.o
Compiling .pioenvs/decoration-lights/libd7c/ESPAsyncWebServer-esphome/WebAuthentication.cpp.o
Archiving .pioenvs/decoration-lights/lib71b/libESP8266WiFi.a
Compiling .pioenvs/decoration-lights/libd7c/ESPAsyncWebServer-esphome/WebHandlers.cpp.o
Compiling .pioenvs/decoration-lights/libd7c/ESPAsyncWebServer-esphome/WebRequest.cpp.o
Compiling .pioenvs/decoration-lights/libd7c/ESPAsyncWebServer-esphome/WebResponses.cpp.o
Compiling .pioenvs/decoration-lights/libd7c/ESPAsyncWebServer-esphome/WebServer.cpp.o
Compiling .pioenvs/decoration-lights/lib73d/DNSServer/DNSServer.cpp.o
Compiling .pioenvs/decoration-lights/libf76/ESP8266mDNS/ESP8266mDNS.cpp.o
Compiling .pioenvs/decoration-lights/libf76/ESP8266mDNS/LEAmDNS.cpp.o
Archiving .pioenvs/decoration-lights/libd7c/libESPAsyncWebServer-esphome.a
Compiling .pioenvs/decoration-lights/libf76/ESP8266mDNS/LEAmDNS_Control.cpp.o
Archiving .pioenvs/decoration-lights/lib73d/libDNSServer.a
Compiling .pioenvs/decoration-lights/libf76/ESP8266mDNS/LEAmDNS_Helpers.cpp.o
Compiling .pioenvs/decoration-lights/libf76/ESP8266mDNS/LEAmDNS_Structs.cpp.o
Compiling .pioenvs/decoration-lights/libf76/ESP8266mDNS/LEAmDNS_Transfer.cpp.o
Archiving .pioenvs/decoration-lights/libFrameworkArduinoVariant.a
Compiling .pioenvs/decoration-lights/FrameworkArduino/Crypto.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/Esp-frag.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/Esp-version.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/Esp.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/FS.cpp.o
Archiving .pioenvs/decoration-lights/libf76/libESP8266mDNS.a
Compiling .pioenvs/decoration-lights/FrameworkArduino/FSnoop.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/FunctionalInterrupt.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/HardwareSerial.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/IPAddress.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/LwipDhcpServer-NonOS.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/LwipDhcpServer.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/LwipIntf.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/LwipIntfCB.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/MD5Builder.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/Print.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/Schedule.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/StackThunk.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/Stream.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/StreamSend.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/Tone.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/TypeConversion.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/Updater.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/WMath.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/WString.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/abi.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/aes_unwrap.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/base64.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/cbuf.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/cont.S.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/cont_util.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_app_entry_noextra4k.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_eboot_command.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_features.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_flash_quirks.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_flash_utils.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_i2s.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_main.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_non32xfer.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_noniso.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_phy.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_postmortem.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_si2c.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_sigma_delta.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_spi_utils.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_timer.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_vm.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_waveform_phase.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_waveform_pwm.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_wiring.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_wiring_analog.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_wiring_digital.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_wiring_pulse.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_wiring_pwm.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/core_esp8266_wiring_shift.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/crc32.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/debug.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/exc-c-wrapper-handler.S.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/exc-sethandler.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/flash_hal.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/gdb_hooks.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/heap.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/hwdt_app_entry.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/libb64/cdecode.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/libb64/cencode.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/libc_replacements.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/mmu_iram.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/reboot_uart_dwnld.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/spiffs/spiffs_cache.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/spiffs/spiffs_check.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/spiffs/spiffs_gc.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/spiffs/spiffs_hydrogen.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/spiffs/spiffs_nucleus.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/spiffs_api.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/sqrt32.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/stdlib_noniso.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/time.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/uart.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/umm_malloc/umm_info.c.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/umm_malloc/umm_integrity.c.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/umm_malloc/umm_local.c.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/umm_malloc/umm_malloc.cpp.o
Compiling .pioenvs/decoration-lights/FrameworkArduino/umm_malloc/umm_poison.c.o
Archiving .pioenvs/decoration-lights/libFrameworkArduino.a
Linking .pioenvs/decoration-lights/firmware.elf
RAM:   [====      ]  40.1% (used 32848 bytes from 81920 bytes)
Flash: [====      ]  40.2% (used 411965 bytes from 1023984 bytes)
Building .pioenvs/decoration-lights/firmware.bin
esp8266_copy_factory_bin([".pioenvs/decoration-lights/firmware.bin"], [".pioenvs/decoration-lights/firmware.elf"])
========================= [SUCCESS] Took 53.78 seconds =========================
INFO Successfully compiled program.
INFO Connecting to 192.168.1.26
INFO Uploading /config/.esphome/build/decoration-lights/.pioenvs/decoration-lights/firmware.bin (416112 bytes)
INFO Compressed to 291748 bytes
Uploading: [============================================================] 100% Done...

INFO Upload took 11.06 seconds, waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
Traceback (most recent call last):
  File "/usr/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/esphome/__main__.py", line 1061, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/esphome/__main__.py", line 1048, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/esphome/__main__.py", line 507, in command_run
    return show_logs(config, args, port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/esphome/__main__.py", line 376, in show_logs
    from esphome.components.api.client import run_logs
  File "/usr/lib/python3.11/site-packages/esphome/components/api/client.py", line 8, in <module>
    from aioesphomeapi import APIClient
  File "/usr/lib/python3.11/site-packages/aioesphomeapi/__init__.py", line 2, in <module>
    from .api_pb2 import (  # type: ignore[attr-defined] # noqa: F401
  File "/usr/lib/python3.11/site-packages/aioesphomeapi/api_pb2.py", line 17, in <module>
    from . import api_options_pb2 as api__options__pb2
  File "/usr/lib/python3.11/site-packages/aioesphomeapi/api_options_pb2.py", line 52, in <module>
    google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(needs_setup_connection)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'MethodOptions' has no attribute 'RegisterExtension'
```

**Comment by hydazz** [comment]
> Same here. Searched error and tried the steps here [https://github.com/esphome/issues/issues/5637#issuecomment-2020258132](url) but no improvement.

That was the fix... 🧐
try changing your image to `ghcr.io/imagegenius/igpipepr-esphome:2024.3.1-pr-8`, lmk if it works.

**Comment by tamimology** [comment]
I am getting this when I pull the image
```
Error response from daemon: Head "https://ghcr.io/v2/imagegenius/igpipepr-esphome/manifests/2024.3.1-pr-8": unauthorized
```

**Comment by hydazz** [comment]
> I am getting this when I pull the image
> 
> ```
> Error response from daemon: Head "https://ghcr.io/v2/imagegenius/igpipepr-esphome/manifests/2024.3.1-pr-8": unauthorized
> ```

sorry, try that again

**Comment by tamimology** [comment]
I can confirm the logs issue is resolved, but it is showing an online (with an update) device, even though this device is actually not connected and should be offline!!!!

![image](https://github.com/imagegenius/docker-esphome/assets/90429593/680aa9df-151d-4cab-ad51-af28245246cd)

**Comment by idontcare99999** [comment]
Works again. Thank you for your timely response.

**Comment by tamimology** [comment]
One more thing I noticed when I install a new device firmware (not update), I am getting the below comment to take care of when you publish the new version

![image](https://github.com/imagegenius/docker-esphome/assets/90429593/d0e5e794-644f-4521-94c1-debf88d5f4ba)

**Comment by hydazz** [comment]
> One more thing I noticed when I install a new device firmware (not update), I am getting the below comment to take care of when you publish the new version
> 
> ![image](https://private-user-images.githubusercontent.com/90429593/318192764-d0e5e794-644f-4521-94c1-debf88d5f4ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NjU2NDQsIm5iZiI6MTcxMTg2NTM0NCwicGF0aCI6Ii85MDQyOTU5My8zMTgxOTI3NjQtZDBlNWU3OTQtNjQ0Zi00NTIxLTk0YzEtZGViZjg4ZDVmNGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA2MDkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNzM4NGExOTc3ZTEyMWI0Yjg2MWQzMjE0NjE0NTAwZmFmMzMwMTk5MzMwOTI0ZDQzM2RkYmZjYTc5MDk1NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bpahXb_p2F2aqswt-WudJl_Dh7LFDEMTYHUdKZ4cPS8)

This is expected, the ESPHome recommended version of PlatformIO is not always the latest version available.
